"use client";

import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import VendorProducts from "@/components/VendorProducts";
import EditProductDialog from "@/components/EditProductDialog";
import { useSupabase } from "@/contexts/SupabaseContext";
import { toast } from "sonner";

interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  quantityUnit: string;
  imageUrl: string;
  minOrderQuantity: number;
  availableQuantity: number;
  vendorName: string;
  category: string;
  vendorRating: number;
  latitude?: number;
  longitude?: number;
  vendor_id?: string; // Add vendor_id to the Product interface
}

const VendorDashboard = () => {
  const { supabase } = useSupabase();
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const [isNewProduct, setIsNewProduct] = useState(false);

  const fetchVendorProducts = async () => {
    setLoading(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      setError("User not authenticated.");
      setLoading(false);
      return;
    }

    const { data, error } = await supabase
      .from("products")
      .select("*")
      .eq("vendor_id", user.id);

    if (error) {
      console.error("Error fetching vendor products:", error);
      setError("Failed to load products.");
      setProducts([]);
    } else {
      setProducts(data as Product[]);
      setError(null);
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchVendorProducts();

    // Set up real-time subscription for vendor's own products
    const channel = supabase
      .channel("vendor_products_changes")
      .on(
        "postgres_changes",
        {
          event: "*",
          schema: "public",
          table: "products",
          filter: `vendor_id=eq.${supabase.auth.getUser().then(u => u.data.user?.id)}`, // Filter by current vendor's ID
        },
        (payload) => {
          console.log("Change received!", payload);
          fetchVendorProducts(); // Re-fetch products on any change
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [supabase]);

  const handleEditProduct = (product: Product) => {
    setSelectedProduct(product);
    setIsNewProduct(false);
    setIsEditDialogOpen(true);
  };

  const handleAddNewProduct = () => {
    setSelectedProduct({
      id: "", // Will be generated by Supabase
      name: "",
      description: "",
      price: 0,
      quantityUnit: "per kg",
      imageUrl: "/placeholder.svg",
      minOrderQuantity: 1,
      availableQuantity: 0,
      vendorName: "", // Will be filled by current user's profile or default
      category: "Vegetables",
      vendorRating: 0, // Default rating
    });
    setIsNewProduct(true);
    setIsEditDialogOpen(true);
  };

  const handleSaveProduct = async (updatedProduct: Product) => {
    setLoading(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      toast.error("Authentication required to save product.");
      setLoading(false);
      return;
    }

    let result;
    if (isNewProduct) {
      // For new products, we need to ensure vendor_id and vendorName are set
      const vendorProfile = await supabase.from('profiles').select('first_name, last_name').eq('id', user.id).single();
      const vendorFullName = vendorProfile.data ? `${vendorProfile.data.first_name || ''} ${vendorProfile.data.last_name || ''}`.trim() : 'Unknown Vendor';

      result = await supabase
        .from("products")
        .insert({
          ...updatedProduct,
          vendor_id: user.id,
          vendorName: vendorFullName,
        })
        .select();
    } else {
      result = await supabase
        .from("products")
        .update(updatedProduct)
        .eq("id", updatedProduct.id)
        .eq("vendor_id", user.id) // Ensure only the owner can update
        .select();
    }

    if (result.error) {
      console.error("Error saving product:", result.error);
      toast.error(`Failed to save product: ${result.error.message}`);
    } else {
      toast.success("Product saved successfully!");
      fetchVendorProducts(); // Re-fetch to update the list
    }
    setLoading(false);
    setIsEditDialogOpen(false);
  };

  const handleDeleteProduct = async (productId: string) => {
    if (!window.confirm("Are you sure you want to delete this product?")) {
      return;
    }

    setLoading(true);
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      toast.error("Authentication required to delete product.");
      setLoading(false);
      return;
    }

    const { error } = await supabase
      .from("products")
      .delete()
      .eq("id", productId)
      .eq("vendor_id", user.id); // Ensure only the owner can delete

    if (error) {
      console.error("Error deleting product:", error);
      toast.error(`Failed to delete product: ${error.message}`);
    } else {
      toast.success("Product deleted successfully!");
      fetchVendorProducts(); // Re-fetch to update the list
    }
    setLoading(false);
  };

  // Placeholder for new order notification
  const simulateNewOrder = () => {
    toast.info("🔔 New Order Received! Check your orders page. (Consider updating your profile if needed!)");
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-gray-950">
        <p className="text-lg text-gray-600 dark:text-gray-300">Loading products...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-gray-50 dark:bg-gray-950 p-4">
        <p className="text-lg text-red-600 dark:text-red-400 mb-4">{error}</p>
        <Button onClick={fetchVendorProducts}>Retry Loading Products</Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col items-center bg-gray-50 dark:bg-gray-950 p-4">
      <div className="w-full max-w-6xl mx-auto py-8">
        <h1 className="text-4xl font-bold mb-4 text-gray-800 dark:text-gray-100 text-center">Vendor Dashboard</h1>
        <p className="text-lg text-gray-600 dark:text-gray-300 mb-8 text-center">
          Welcome, vendor! Here you can manage your listed products.
        </p>
        
        <div className="flex justify-center gap-4 mb-8">
          <Button 
            onClick={handleAddNewProduct}
            className="px-6 py-3 text-lg bg-green-600 hover:bg-green-700 text-white shadow-lg transform transition-transform hover:scale-105"
          >
            Add New Product
          </Button>
          <Button 
            onClick={simulateNewOrder}
            variant="outline"
            className="px-6 py-3 text-lg border-blue-600 text-blue-600 hover:bg-blue-50 dark:border-blue-400 dark:text-blue-400 dark:hover:bg-gray-700 shadow-lg transform transition-transform hover:scale-105"
          >
            Simulate New Order Notification
          </Button>
        </div>

        <h2 className="text-3xl font-semibold mb-6 text-gray-800 dark:text-gray-100 text-center">Your Listed Products</h2>
        <VendorProducts products={products} onEdit={handleEditProduct} onDelete={handleDeleteProduct} />

        <div className="mt-12 text-center">
          <Link to="/">
            <Button variant="outline" className="px-6 py-3 text-lg border-green-600 text-green-600 hover:bg-green-50 dark:border-green-400 dark:text-green-400 dark:hover:bg-gray-700 shadow-lg transform transition-transform hover:scale-105">
              Back to Home
            </Button>
          </Link>
        </div>
      </div>

      <EditProductDialog
        isOpen={isEditDialogOpen}
        onClose={() => setIsEditDialogOpen(false)}
        product={selectedProduct}
        onSave={handleSaveProduct}
      />
    </div>
  );
};

export default VendorDashboard;