// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://suajiackxlkcfnpmffzz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1YWppYWNreGxrY2ZucG1mZnp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0MjQyMjAsImV4cCI6MjA4MzAwMDIyMH0.z_O9B6JfnhNsz2efnZ4rCjgIPBcZ54RMbcNtmGexsXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);